[package]
name = "rust_server"
version = "0.1.0"
authors = ["Riccardo Felluga <rfelluga@unibz.it>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
juniper = "0.13.0"
rocket = "0.4.2"

